name: todoapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  table_calendar: ^2.2.3
  datetime_picker_formfield: ^1.0.0
  provider: ^4.0.5+1
  sqflite: ^1.3.0
  path_provider: ^1.6.7
  intl: ^0.16.1
  percent_indicator: ^2.1.3
  step_progress_indicator: ^0.2.2+5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

